### ISSUE TITLE
CentOS 7 Compatibility?

### ISSUE THREAD

**Issue by dahjelle** [wendall911/couchdb-rpm#16]

**Comment by wendall911** [comment]
It will be working soon with Centos 7. I was supposed to work on this over the weekend, but got delayed with other things. I'll have this tested and updated soon. Sorry for the delay. Expect this in the next couple of days.

**Comment by dahjelle** [comment]
Awesome! I tried my hand at compiling Couch on CentOS manually. That works fine if I start it from the command line, but I had no luck getting it to run on boot under systemd. Very curious to see what the trick is!

**Comment by wendall911** [comment]
@dch @dahjelle Thank you for saving me time on this. Very helpful. I'll get some work on this here soon. Thanks for the research on this, very appreciated.

**Comment by dahjelle** [comment]
@wendall911 Glad if it is helpful! FYI, I just added a few more comments to the SO question, as I found that creating an admin user and running a view also hit SELinux issues.

**Comment by gtirloni** [comment]
Just wanted to report that on a fresh install of CentOS 7.1.1503 x86_64 with CouchDB 1.6.1 from EPEL, I only get crash reports when trying to access http://127.0.0.1:5984.

    [Sat, 27 Jun 2015 00:09:56 GMT] [info] [<0.31.0>] Apache CouchDB has started on http://127.0.0.1:5984/
    [Sat, 27 Jun 2015 00:10:11 GMT] [error] [<0.125.0>] {error_report,<0.30.0>,
	                     {<0.125.0>,crash_report,
	                      [[{initial_call,
	                         {mochiweb_acceptor,init,
	                          ['Argument__1','Argument__2','Argument__3']}},
	                        {pid,<0.125.0>},
	                        {registered_name,[]},
	                        {error_info,
	                         {error,undef,
	                          [{mochiweb_util,partition,[[],"/"],[]},
	                           {couch_httpd,handle_request_int,5,
	                            [{file,"couch_httpd.erl"},{line,243}]},
	                           {mochiweb_http,headers,5,
	                            [{file,"src/mochiweb_http.erl"},{line,94}]},
	                           {proc_lib,init_p_do_apply,3,
	                            [{file,"proc_lib.erl"},{line,239}]}]}},
	                        {ancestors,
	                         [couch_httpd,couch_secondary_services,
	                          couch_server_sup,<0.31.0>]},
	                        {messages,[]},
	                        {links,[<0.109.0>,#Port<0.4980>]},
	                        {dictionary,[{couch_rewrite_count,0}]},
	                        {trap_exit,false},
	                        {status,running},
	                        {heap_size,2586},
	                        {stack_size,27},
	                        {reductions,1767}],
	                       []]}}

**Comment by macropin** [comment]
@dahjelle I wouldn't worry about systemd. Just find another way to spawn the process. Eg write a shell script and use exec, or background the process and watch for exit, or use another process manager that won't get in the way. This is how we do it [using voltgrid pie](https://github.com/panubo/Dockerfiles/tree/master/couchdb). I came here because [EPEL7 has retired CouchDB](http://pkgs.fedoraproject.org/cgit/rpms/couchdb.git/commit/?h=epel7) due to a orphaned dependency.

**Comment by fatmcgav** [comment]
Any joy on this? Could do with getting CouchDB working on EL7 in a sane manner :)

**Comment by fatmcgav** [comment]
So I ploughed on this afternoon and managed to get a CentOS 7 RPM built successfully, with a few minimal tweaks to the spec file and systemd unit file. 

PR #19 raised.

**Comment by wendall911** [comment]
@fatmcgav Much appreciated. Sorry, I've been super busy lately. I'll get this tested and merged in as soon as I can, probably by tomorrow at the latest.

**Comment by wendall911** [comment]
Apologies to all that I've been neglecting this. I'll make sure to get it updated shortly.

**Comment by wendall911** [comment]
CentOS 7 support is now merged in.
