### ISSUE TITLE
possibly undefined macro: AC_DEFINE

### ISSUE THREAD

**Issue by cmadsen** [wendall911/couchdb-rpm#17]
I get a `possibly undefined macro: AC_DEFINE` when doing rpmbild

rpmbuild --rebuild ~/rpmbuild/SRPMS/couchdb-1.6.1-1.el6.src.rpm 
Installing /root/rpmbuild/SRPMS/couchdb-1.6.1-1.el6.src.rpm
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.20KXLa
+ umask 022
+ cd /root/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /root/rpmbuild/BUILD
+ rm -rf apache-couchdb-1.6.1
+ /bin/tar -xf -
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/apache-couchdb-1.6.1.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd apache-couchdb-1.6.1
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #1 (couchdb-0001-Do-not-gzip-doc-files-and-do-not-install-installatio.patch):'
Patch #1 (couchdb-0001-Do-not-gzip-doc-files-and-do-not-install-installatio.patch):
+ /usr/bin/patch -p1 -b --suffix .dont_gzip --fuzz=0
+ /bin/cat /root/rpmbuild/SOURCES/couchdb-0001-Do-not-gzip-doc-files-and-do-not-install-installatio.patch
patching file Makefile.am
+ echo 'Patch #2 (couchdb-0002-Install-docs-into-versioned-directory.patch):'
Patch #2 (couchdb-0002-Install-docs-into-versioned-directory.patch):
+ /usr/bin/patch -p1 -b --suffix .use_versioned_docdir --fuzz=0
+ /bin/cat /root/rpmbuild/SOURCES/couchdb-0002-Install-docs-into-versioned-directory.patch
patching file configure.ac
Hunk #1 succeeded at 691 (offset 12 lines).
+ echo 'Patch #3 (couchdb-0003-More-directories-to-search-for-place-for-init-script.patch):'
Patch #3 (couchdb-0003-More-directories-to-search-for-place-for-init-script.patch):
+ /usr/bin/patch -p1 -b --suffix .more_init_dirs --fuzz=0
+ /bin/cat /root/rpmbuild/SOURCES/couchdb-0003-More-directories-to-search-for-place-for-init-script.patch
patching file configure.ac
Hunk #1 succeeded at 528 (offset 4 lines).
+ echo 'Patch #4 (couchdb-0004-Install-into-erllibdir-by-default.patch):'
Patch #4 (couchdb-0004-Install-into-erllibdir-by-default.patch):
+ /usr/bin/patch -p1 -b --suffix .install_into_erllibdir --fuzz=0
+ /bin/cat /root/rpmbuild/SOURCES/couchdb-0004-Install-into-erllibdir-by-default.patch
patching file configure.ac
Hunk #1 succeeded at 698 (offset 4 lines).
Hunk #2 succeeded at 711 (offset 4 lines).
+ sed -i -e 's,prove,prove -v,g' test/etap/run.tpl
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.FJKkf9
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd apache-couchdb-1.6.1
+ LANG=C
+ export LANG
+ unset DISPLAY
+ autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:66: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:328: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
error: Bad exit status from /var/tmp/rpm-tmp.FJKkf9 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.FJKkf9 (%build)

**Comment by n3integration** [comment]
I ran into the same issue while building on a CentOS 6 system. The issue ended up being caused by a missing `autoconf-archive` dependency.

A git repository that includes a spec file and instructions for building the dependency can be found at [autoconf-archive-rpm](https://github.com/meltwater/autoconf-archive-rpm).

**Comment by wendall911** [comment]
I also provide instructions in the README that includes a local repo for building autoconf-archive https://github.com/wendall911/autoconf-archive
