### ISSUE TITLE
Add PID dir creation to service file

### ISSUE THREAD

**Issue by hcderaad** [wendall911/couchdb-rpm#20]
The current service file does not create the directory for the PID file, so starting couchdb works, but then performing any action on it makes it die.

Please add the following lines to the couchdb.service file (before PID file):

PermissionsStartOnly=true
ExecStartPre=/usr/bin/install -o couchdb -g couchdb -d /var/run/couchdb

**Comment by wendall911** [comment]
@hcderaad Thank you for letting me know. I've added it to master and 1.6.x branches.

**Comment by hcderaad** [comment]
Thanks for picking this up so swiftly!
